### ISSUE TITLE
Not working with AA 1.0.0.pre

### ISSUE THREAD

**Issue by baxang** [randym/activeadmin-axlsx#22]
I'm trying to get the gem working with current AA master, 1.0.0.pre and after I made a few tiny fixes  I got my Rails project booted.  But ActiveAdmin resources that use xlsx DSL produces this error:

```
undefined method `xlsx' for #<ActiveAdmin::ResourceDSL:0x007fc4e3294e10> (NoMethodError)
```

And my patch is https://github.com/stripeskr/activeadmin-axlsx/commit/59ea1ff5631c3f277125e4f0115d1b357f7f3bcb

Not sure if it is happening because any recent change of AA, but I can't figure it out. Can anybody help me solving it?

**Comment by baxang** [comment]
The trick introduced in https://github.com/randym/activeadmin-axlsx/pull/19 also fixes this problem as well. I just moved code inside the block in https://github.com/randym/activeadmin-axlsx/blob/master/lib/active_admin/axlsx.rb#L21 to the end of my Rails app's `config/initializers/activeadmin.rb' and it worked.

**Comment by alepore** [comment]
same problem on AA 0.6.3.
edit:
fixed reverting last commits, starting from 06b16f820493e46603150e926150188a5a6a6a93

**Comment by zurzer** [comment]
first download it from github to change something.
git clone https://github.com/randym/activeadmin-axlsx
git clone https://github.com/ywencn/active_admin

make path correct.
gem 'activeadmin-axlsx', path: '../activeadmin-axlsx'
gem 'activeadmin', path: '../activeadmin'

change all below:

for undefined method `xlsx' for #ActiveAdmin::ResourceDSL:0x (NoMethodError)
yourproject/config/environments/production.rb
    set
    config.eager_load = false

for `require': cannot load such file -- activeadmin/axlsx (LoadError) 
activeadmin-axlsx/activeadmin-axlsx.gemspec
  s.add_runtime_dependency 'activeadmin', "~> 0.6.0"
  to
  s.add_runtime_dependency 'activeadmin', "> 0.6.0"

for ArgumentError (wrong number of arguments (1 for 0)):
activeadmin/lib/active_admin/resource_controller/streaming.rb:11:in `index'
    Change line 11
    def index
    to
    def index(arg=nil)

for undefined local variable or method `max_csv_records':
activeadmin-axlsx/lib/active_admin/axlsx/resource_controller_extension.rb:11:in`per_page_with_xlsx'
    add max_csv_records = 1000 # some num which result in db query as limit 1000 in the end of select \* query.

```
  def per_page_with_xlsx
      max_csv_records = 1000   #add
      if request.format ==  Mime::Type.lookup_by_extension(:xlsx)
        return max_csv_records
      end
      per_page_without_xlsx
  end
```
